FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --only-group api

COPY api ./api
COPY configs ./configs
COPY src ./src

EXPOSE 8000

CMD ["uv", "run", "--frozen", "--no-sync", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
